### PR TITLE
Enable renovate

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/marketplace/renovate

### CODE REVIEW

**Comment by Bill13579** [comment]
It seems like renovate does not support Rustlang, see [the doc page](https://docs.renovatebot.com/bazel/) here
Alternatively, Dependabot should work.

**Comment by Bill13579** [comment]
See #111

**Comment by gliptak** [comment]
@Bill13579 I wasn't aware of Rust not being supported by Renovate. with that said, both will support bumping https://github.com/Bill13579/tabby/blob/master/.github/workflows/ci.yml#L18 (which is the current Rust dependency)

I find Renovate to have smarter autoconfiguration

**Comment by gliptak** [comment]
there is also https://github.com/renovatebot/renovate/blob/main/docs/usage/rust.md

i don't know why not linked in https://docs.renovatebot.com/

**Comment by Bill13579** [comment]
> there is also https://github.com/renovatebot/renovate/blob/main/docs/usage/rust.md
> 
> i don't know why not linked in https://docs.renovatebot.com/

Tbf I have no idea why they did not link this in the docs, I would've considered it more if it had

**Comment by Bill13579** [comment]
> @Bill13579 I wasn't aware of Rust not being supported by Renovate. with that said, both will support bumping https://github.com/Bill13579/tabby/blob/master/.github/workflows/ci.yml#L18 (which is the current Rust dependency)
> 
> I find Renovate to have smarter autoconfiguration

From my research it indeed seems to have better automation. However I do want to make sure that the Rust support is not half-baked and is fully supported, Rust is a big part of the codebase now

**Comment by gliptak** [comment]
yes, you are already getting `dependabot` bumps https://github.com/Bill13579/tabby/pulls/app%2Fdependabot

#116 

it would be interesting to compare `renovate` autoconfigure to `dependabot` configured pulls

**Comment by Bill13579** [comment]
Yeah it would be pretty interesting. The grouping features in renovate is admittedly pretty cool and nice too! Both seem like really cool products. For now dependabot seems to be working well, but if the single pr's become too much there will be this pr ready to go; I'll place this as a draft for now.

**Pull request closed without merging**
