### PR TITLE
Remove annoying "everything new" popup

### PR DESCRIPTION
**Pull request by paulius-valiunas**

### CODE REVIEW

**Comment by paulius-valiunas** [comment]
fixes #149

**Comment by paulius-valiunas** [comment]
@Bill13579 please?

**Comment by Bill13579** [comment]
Not sure about completely removing the page, but the new update should fix it popping up on every browser update.

**Comment by Bill13579** [comment]
It might be good to add, but for now the frequency of the page showing is reduced to at most once or twice a year (aka whenever there are updates). I think that's acceptable for now. I'm really busy with other life things at the moment and my focus is already split pretty thin, I'll probably go crazy if I had to work on more things rn.

**Pull request closed without merging**
